"""
Django settings for crm_project project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-dev-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [host.strip() for host in os.getenv(
    'DJANGO_ALLOWED_HOSTS',
    '127.0.0.1,localhost,testserver'
).split(',') if host.strip()]

# Test environment flag
TESTING = 'test' in sys.argv


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crm',  # додав рядок
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'crm.middleware.CSPMiddleware',  # Додаємо CSP middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crm_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'crm/templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crm_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'crm.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'crm': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "crm/static"]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Куди перенаправляти після успішного входу
LOGIN_URL = '/login/'  # вказує на твій шлях до логіну
LOGIN_REDIRECT_URL = '/'  # куди перекидає після успішного входу

# API Keys for external services
# Get free API key from https://openrouteservice.org/
OPENROUTE_API_KEY = os.getenv('OPENROUTE_API_KEY') or None

# External routing calls can be disabled for tests/offline runs
EXTERNAL_ROUTING_ENABLED = (
    os.getenv('EXTERNAL_ROUTING_ENABLED', 'true').lower() in ('1', 'true', 'yes')
    and not TESTING
)

# Simple shared secrets for unauthenticated endpoints (optional)
COURIER_LOCATION_API_KEY = os.getenv('COURIER_LOCATION_API_KEY') or None
PAYMENT_WEBHOOK_SECRET = os.getenv('PAYMENT_WEBHOOK_SECRET') or None

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Для Gmail
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ''  # Ваш email
EMAIL_HOST_PASSWORD = ''  # Пароль приложения Gmail
DEFAULT_FROM_EMAIL = 'CRM System <noreply@crmsystem.com>'

# Настройки уведомлений
EMAIL_NOTIFICATIONS = {
    'ORDER_CREATED': True,
    'ORDER_STATUS_CHANGED': True,
    'PAYMENT_RECEIVED': True,
    'DELIVERY_ASSIGNED': True,
    'DELIVERY_COMPLETED': True,
    'REMINDER_NOTIFICATIONS': True,
}

# Local AI (Ollama) configuration
OLLAMA_URL = os.getenv('OLLAMA_URL', 'http://localhost:11434')
OLLAMA_MODEL = os.getenv('OLLAMA_MODEL', 'gemma3:4b')

# Налаштування безпеки для режиму розробки
if DEBUG:
    # ⚠️ Ці налаштування відключають деякі захисні механізми для зручності розробки
    # В ПРОДАКШЕНІ вони повинні бути включені!
    
    # Відключаємо деякі безпекові перевірки
    SECURE_CONTENT_TYPE_NOSNIFF = False
    SECURE_BROWSER_XSS_FILTER = False
    
    # Відключаємо X-Frame-Options для розробки
    X_FRAME_OPTIONS = 'ALLOWALL'
    
    # CSP налаштування для розробки (більш м'які)
    CSP_DEFAULT_SRC = ["'self'", "'unsafe-inline'", "'unsafe-eval'"]
    CSP_SCRIPT_SRC = ["'self'", "'unsafe-inline'", "'unsafe-eval'", 
                      "https://cdn.jsdelivr.net", "https://cdnjs.cloudflare.com", 
                      "https://use.fontawesome.com", "https://stackpath.bootstrapcdn.com",
                      "https://unpkg.com"]
    CSP_STYLE_SRC = ["'self'", "'unsafe-inline'", 
                     "https://cdn.jsdelivr.net", "https://cdnjs.cloudflare.com", 
                     "https://use.fontawesome.com", "https://stackpath.bootstrapcdn.com",
                     "https://unpkg.com"]
    CSP_FONT_SRC = ["'self'", "https://cdnjs.cloudflare.com", "https://use.fontawesome.com"]
    CSP_IMG_SRC = ["'self'", "data:", "https:", "https://*.tile.openstreetmap.org"]
    CSP_CONNECT_SRC = ["'self'", "https://unpkg.com", "https://*.tile.openstreetmap.org", 
                       "https://api.openrouteservice.org", "https://router.project-osrm.org"]
