# Generated by Django 5.2.5 on 2025-08-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='Невідома адреса', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.CharField(default='Невідома адреса', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(),
        ),
    ]
