# Generated by Django 5.2.6 on 2025-09-03 17:53

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_rename_user_order_created_by_remove_order_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('polygon_data', models.JSONField(help_text='GeoJSON polygon data for the zone')),
                ('base_delivery_time', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('traffic_multiplier', models.FloatField(default=1.0, help_text='Traffic delay multiplier')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='latitude',
            field=models.FloatField(blank=True, help_text="Client's latitude coordinate", null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='longitude',
            field=models.FloatField(blank=True, help_text="Client's longitude coordinate", null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='current_latitude',
            field=models.FloatField(blank=True, help_text='Current latitude', null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='current_longitude',
            field=models.FloatField(blank=True, help_text='Current longitude', null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='vehicle_type',
            field=models.CharField(choices=[('bike', 'Велосипед'), ('motorcycle', 'Мотоцикл'), ('car', 'Автомобіль'), ('van', 'Фургон')], default='bike', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='actual_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_notes',
            field=models.TextField(blank=True, help_text='Special delivery instructions'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Delivery latitude coordinate', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Delivery longitude coordinate', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('low', 'Низький'), ('normal', 'Звичайний'), ('high', 'Високий'), ('urgent', 'Терміновий')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Нове'), ('assigned', 'Призначено'), ('picked_up', 'Забрано'), ('in_transit', 'В дорозі'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Route name or identifier', max_length=100)),
                ('status', models.CharField(choices=[('planned', 'Заплановано'), ('active', 'Активний'), ('completed', 'Завершено'), ('cancelled', 'Скасовано')], default='planned', max_length=20)),
                ('total_distance', models.FloatField(blank=True, help_text='Total route distance in km', null=True)),
                ('estimated_duration', models.DurationField(blank=True, null=True)),
                ('actual_duration', models.DurationField(blank=True, null=True)),
                ('route_data', models.JSONField(blank=True, help_text='Optimized route coordinates', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.courier')),
            ],
        ),
        migrations.CreateModel(
            name='RouteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='Order of delivery in the route')),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.order')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.deliveryroute')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('route', 'sequence')},
            },
        ),
        migrations.AddField(
            model_name='deliveryroute',
            name='orders',
            field=models.ManyToManyField(through='crm.RouteOrder', to='crm.order'),
        ),
        migrations.CreateModel(
            name='CourierLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Speed in km/h', null=True)),
                ('bearing', models.FloatField(blank=True, help_text='Direction in degrees', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='crm.courier')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['courier', '-timestamp'], name='crm_courier_courier_6ccd64_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField(help_text='Hour of day (0-23)')),
                ('day_of_week', models.IntegerField(help_text='Day of week (0=Monday, 6=Sunday)')),
                ('average_delay_factor', models.FloatField(default=1.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.deliveryzone')),
            ],
            options={
                'unique_together': {('zone', 'hour', 'day_of_week')},
            },
        ),
    ]
