# Generated by Django 5.2.5 on 2025-09-03 18:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_deliveryzone_client_latitude_client_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_fees',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional fees (urgent, weight, etc.)', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base delivery price', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final price', max_digits=10),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Готівка'), ('card', 'Банківська картка'), ('online', 'Онлайн оплата'), ('bank_transfer', 'Банківський переказ'), ('postpaid', 'Післяплата')], default='cash', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Очікується'), ('processing', 'В обробці'), ('completed', 'Завершено'), ('failed', 'Помилка'), ('refunded', 'Повернено'), ('cancelled', 'Скасовано')], default='pending', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_received', models.DecimalField(blank=True, decimal_places=2, help_text='Amount received in cash', max_digits=10, null=True)),
                ('change_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Change to give back', max_digits=10, null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='External payment transaction ID', max_length=100, null=True)),
                ('gateway_response', models.JSONField(blank=True, help_text='Payment gateway response data', null=True)),
                ('payment_notes', models.TextField(blank=True, help_text='Additional payment notes')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='crm.order')),
                ('processed_by', models.ForeignKey(blank=True, help_text='User who processed the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
