# Generated by Django 5.2.6 on 2025-09-04 07:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_order_additional_fees_order_base_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Широта клієнта', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Довгота клієнта', null=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='current_latitude',
            field=models.FloatField(blank=True, help_text='Поточна широта', null=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='current_longitude',
            field=models.FloatField(blank=True, help_text='Поточна довгота', null=True),
        ),
        migrations.AlterField(
            model_name='courierlocation',
            name='accuracy',
            field=models.FloatField(blank=True, help_text='Точність GPS в метрах', null=True),
        ),
        migrations.AlterField(
            model_name='courierlocation',
            name='bearing',
            field=models.FloatField(blank=True, help_text='Напрямок в градусах', null=True),
        ),
        migrations.AlterField(
            model_name='courierlocation',
            name='speed',
            field=models.FloatField(blank=True, help_text='Швидкість в км/г', null=True),
        ),
        migrations.AlterField(
            model_name='deliveryroute',
            name='name',
            field=models.CharField(help_text='Назва маршруту або ідентифікатор', max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveryroute',
            name='route_data',
            field=models.JSONField(blank=True, help_text='Оптимізовані координати маршруту', null=True),
        ),
        migrations.AlterField(
            model_name='deliveryroute',
            name='total_distance',
            field=models.FloatField(blank=True, help_text='Загальна відстань маршруту в км', null=True),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='polygon_data',
            field=models.JSONField(help_text='Дані полігону GeoJSON для зони'),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='traffic_multiplier',
            field=models.FloatField(default=1.0, help_text='Множник затримки через трафік'),
        ),
        migrations.AlterField(
            model_name='order',
            name='additional_fees',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Додаткові платежі (терміново, вага тощо)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Базова ціна доставки', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_notes',
            field=models.TextField(blank=True, help_text='Особливі інструкції доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Сума знижки', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Широта доставки', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Довгота доставки', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Кінцева ціна', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cash_received',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Сума отримана готівкою', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='change_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Здача до повернення', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_response',
            field=models.JSONField(blank=True, help_text='Дані відповіді платіжного шлюзу', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_notes',
            field=models.TextField(blank=True, help_text='Додаткові примітки платежу'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='Користувач, який обробив платіж', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Зовнішній ID транзакції платежу', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='routeorder',
            name='sequence',
            field=models.PositiveIntegerField(help_text='Порядок доставки в маршруті'),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='day_of_week',
            field=models.IntegerField(help_text='День тижня (0=Понеділок, 6=Неділя)'),
        ),
        migrations.AlterField(
            model_name='trafficdata',
            name='hour',
            field=models.IntegerField(help_text='Година дня (0-23)'),
        ),
        migrations.CreateModel(
            name='EmailNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_order_created', models.BooleanField(default=True, verbose_name='Уведомления о создании заказа')),
                ('notify_order_status_changed', models.BooleanField(default=True, verbose_name='Уведомления об изменении статуса')),
                ('notify_payment_received', models.BooleanField(default=True, verbose_name='Уведомления о получении платежа')),
                ('notify_delivery_assigned', models.BooleanField(default=True, verbose_name='Уведомления о назначении курьера')),
                ('notify_delivery_completed', models.BooleanField(default=True, verbose_name='Уведомления о завершении доставки')),
                ('receive_new_order_notifications', models.BooleanField(default=True, verbose_name='Получать уведомления о новых заказах')),
                ('receive_payment_notifications', models.BooleanField(default=True, verbose_name='Получать уведомления о платежах')),
                ('receive_delivery_assignments', models.BooleanField(default=True, verbose_name='Получать уведомления о назначениях')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки email уведомлений',
                'verbose_name_plural': 'Настройки email уведомлений',
            },
        ),
    ]
