# Generated by Django 5.2.6 on 2025-09-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_client_latitude_alter_client_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, help_text='Email клиента для уведомлений', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='email',
            field=models.EmailField(blank=True, help_text='Email курьера для уведомлений', max_length=254, null=True),
        ),
    ]
